### ISSUE TITLE
Callback de prateleiras

### ISSUE THREAD

**Issue by zeluizr** [caljp13/VTEX-Smart-Research#1]
Fala ai Carlos,
Mesmo problema que tive com o infinity scroll.

Eu quero que quando retorne ele devolta o HTML do /buscapagina somente a parte dentro da UL, quer dizer somente os LIs, porque eu uso uma versão do css, que não tem ULs só um UL e todas as LIs dentro.

Obrigado!

**Comment by cvscarlos** [comment]
@zeluizr esse plugin não é atualizado faz tempo, ao menos não para a comunidade. O [`Infinity Scroll`](https://github.com/caljp13/QD-Infinity-Scroll) é o único que mantemos atualizado para todos.

Mas respondendo sua pergunta, se você estiver conseguindo utilizá-lo sem problemas ok. Para fazer o que você deseja, infelizmente não existe callback, mas você pode tentar customizar a linha [#177](https://github.com/caljp13/VTEX-Smart-Research/blob/master/vtex-smartResearch.js#L177) no mesmo principio que a outra solução.
